site_name: AttendOn
theme: 
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - announce.dismiss
    - header.autohide
    - search.suggest
    - search.highlight
    - toc.integrate
    - navigation.indexes
    - navigation.tabs
  language: en 
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: blue 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  nav:
    - Home: index.md
    - Example: example.md
    - About: about.md 
  logo:
    file: img/logo.png
    height: 150
    width: 150
  favicon: img/logo.png