site_name: My Docs
theme: 
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - anounce.dismiss
    - header.autohide
    - search.suggest
    - search.highlight
    - search.share
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.footer
nav:
  - Home: index.md
  - About: about.md
  - Example: example.md 
